version: "3.7"

networks:
  fixed_compose_network:
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/24

services:
  cyclox2_svr:
    build: "./cyclox2_svr/"
    image: "kyamady/img_cyclox2_svr"
    container_name: "cyclox2_svr"
    ports:
      - 80:80
      - 443:8443
    volumes:
      - ./cyclox2_svr/httpd/conf/httpd.conf:/etc/httpd/conf/httpd.conf
      - ./cyclox2_svr/httpd/conf/magic:/etc/httpd/conf/magic
      - ./cyclox2_svr/httpd/conf.d/ssl.conf:/etc/httpd/conf.d/ssl.conf
      - ./cyclox2_svr/php/php.ini:/usr/local/etc/php/php.ini
      - ./cyclox2_svr/pki/tls/certs/server.key:/etc/pki/tls/certs/server.key
      - ./cyclox2_svr/pki/tls/certs/server.csr:/etc/pki/tls/certs/server.csr
      - ./cyclox2_svr/pki/tls/certs/server.crt:/etc/pki/tls/certs/server.crt
      - ./cyclox2_svr/cyclox2/app/tmp/logs:/var/www/html/logs
      - ./cyclox2_svr/cyclox2:/var/www/html
      - ./cyclox2_svr/cyclox2_conf/htaccess_cyclox2:/var/www/html/.htaccess
      - ./cyclox2_svr/cyclox2_conf/htaccess_webroot:/var/www/html/app/webroot/.htaccess
      - ./cyclox2_svr/cyclox2_conf/database.php:/var/www/html/app/Config/database.php
    depends_on:
      - cyclox2_mysql
    user: 0:0
    networks:
      fixed_compose_network:
        ipv4_address: 172.24.0.2

  cyclox2_mysql:
    build: "./cyclox2_mysql/"
    image: "kyamady/img_cyclox2_mysql"
    container_name: "cyclox2_mysql"
    ports:
      - 3306:3306
    volumes:
      - ./cyclox2_mysql/var/mysql:/var/lib/mysql
      - ./cyclox2_mysql/var/dump:/var/tmp
      - ./cyclox2_mysql/conf/my.cnf:/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: Yamaken0
      MYSQL_PORT: 3306
    networks:
      fixed_compose_network:
        ipv4_address: 172.24.0.3

  cyclox2_mysql_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "cyclox2_phpmyadmin"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=cyclox2_mysql #mysqlサービス名を指定
      - PMA_USER=root
      - PMA_PASSWORD=Yamaken0
    links:
      - cyclox2_mysql
    ports:
      - 4040:80
    volumes:
      - ./phpmyadmin/sessions:/sessions
    networks:
      fixed_compose_network:
        ipv4_address: 172.24.0.4

  cyclox2ressys_svr:
    build: "./cyclox2ressys_svr/"
    image: "kyamady/img_cyclox2ressys_svr"
    container_name: "cyclox2ressys_svr"
    ports:
      - 8081:80
    volumes:
      - ./cyclox2ressys_svr/httpd/conf/httpd.conf:/etc/httpd/conf/httpd.conf
      - ./cyclox2ressys_svr/conf/database.php:/var/www/html/ajocc_xsys/application/config/database.php
      - ./cyclox2ressys_svr/conf/config.php:/var/www/html/ajocc_xsys/application/config/config.php
      - ./cyclox2ressys_svr/conf/index.php:/var/www/html/ajocc_xsys/public/index.php
    environment:
      DB_HOSTNAME: cyclox2_mysql
      DB_USERNAME: root
      DB_PASSWORD: Yamaken0
      DB_DATABASE: cyclox2
    depends_on:
      - cyclox2_mysql
    user: 0:0
    networks:
      fixed_compose_network:
        ipv4_address: 172.24.0.5
